all:weakptr1 weakptr2 enableshared1

weakptr1:weakptr1.cpp
	g++  weakptr1.cpp -o weakptr1 -std=c++11
weakptr2:weakptr2.cpp
	g++ weakptr2.cpp -o weakptr2 -std=c++11
enableshared1:enableshared1.cpp
	g++ enableshared1.cpp -o enableshared1 -std=c++11
clean:
	rm -rf weakptr1 weakptr2 enableshared1
