all:multiset1 multimap1 set1 unordered_map1 unordmultiset1 unordmultiset2 assoarray1
multiset1:
	g++ multiset1.cpp -o multiset1 -std=c++11
multimap1:
	g++ multimap1.cpp -o multimap1 -std=c++11
set1:
	g++ set1.cpp -o set1 -std=c++11
unordered_map1:
	g++ unordered_map1.cpp -o unordered_map1 -std=c++11
unordmultiset1:
	g++ unordmultiset1.cpp -o unordmultiset1 -std=c++11
unordmultiset2:
	g++ unordmultiset2.cpp -o unordmultiset2 -std=c++11
assoarray1:
	g++ assoarray1.cpp -o assoarray1 -std=c++11
clean:
	rm -rf multiset1 multimap1 set1 unorderd_map1 unordmultiset1 unordmultiset2 assoarray1
