all:list1 list2 list1old
list1:list1.cpp
	g++ list1.cpp -o list1 -std=c++11
list2:
	g++ list2.cpp -o list2 -std=c++11
list1old:
	g++ list1old.cpp -o list1old -std=c++11
clean:
	rm -rf list1 list2 list1old
