all:remove1 remove2 remove3 remove4
remove1:
	g++ remove1.cpp -o remove1 -std=c++11
remove2:
	g++ remove2.cpp -o remove2 -std=c++11
remove3:
	g++ remove3.cpp -o remove3 -std=c++11
remove4:
	g++ remove4.cpp -o remove4 -std=c++11
clean:
	rm -rf remove1 remove2 remove3
