all:chrono1 chrono2 clock1 timepoint1
chrono1:chrono1.cpp
	g++ chrono1.cpp -o chrono1 -std=c++11
chrono2:chrono2.cpp
	g++ chrono2.cpp -o chrono2 -std=c++11
clock1:clock1.cpp clock.hpp
	g++ clock1.cpp -o clock1 -std=c++11
timepoint1:timepoint1.cpp timepoint.hpp
	g++ timepoint1.cpp -o timepoint1 -std=c++11
clean:
	rm -rf chrono1 chrono2 clock1 timepoint1
