all:vector1 reviter1 vector2
vector1:vector1.cpp
	g++ vector1.cpp -o vector1 -std=c++11
reviter1:
	g++ reviter1.cpp -o reviter1 -std=c++11
vector2:
	g++ vector2.cpp -o vector2 -std=c++11
clean:
	rm -rf vector1 reviter1 vector2
