all:foreach2 add1 fo1 bind1
foreach2:
	g++ foreach2.cpp -o foreach2 -std=c++11
add1:print.hpp
	g++ add1.cpp -o add1 -std=c++11
fo1:
	g++ fo1.cpp -o fo1 -std=c++11
bind1:
	g++ bind1.cpp -o bind1 -std=c++11
clean:
	rm -rf foreach2 add1 fo1 bind1
